default:
  max_reflection_round: 3

  generator : 
    model_class: ChatOpenAI
    model_params:
      model: gpt-4.1-mini
      temperature : 0.0
      top_p : 0.0

  critic: 
    model_class: ChatOpenAI
    model_params:
      model: gpt-4.1-mini
      temperature : 0.0
      top_p : 0.0

  assets:
    binance: 
      Bitcoin: BTCUSDT
      Ethereum: ETHUSDT
      Ripple: XRPUSDT
      Binance Coin: BNBUSDT
      Solana: SOLUSDT
      Chainlink: LINKUSDT
    nasdaq:
      Meta: META
      Nvidia : NVDA
      Tesla : TSLA
      Palantir: PLTR
      Microsoft : MSFT
      Alphabet (Google) : GOOGL
